config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
      resources :states do
        member do
          get :make_default
        end
      end

      put "permissions", to: "permissions#set",
                        as: "set_permissions"
    end
  end

  root "projects#index"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"

  delete "/signout", to: "sessions#destroy", as: "signout"

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  resources :users
  resources :files
end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tickets, dependent: :delete_all
  validates :name, presence: true

  has_many :permissions, as: :thing
  scope :for, ->(user) do
    user.admin? ? Project.all : Project.viewable_by(user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authorize_admin!, except: [:index, :show]
  before_action :require_signin!, only: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.for(current_user)
  end

  def new
    @project = Project.new
  end

  def show
  #  @project = Project.find(params[:id])
  end

  def edit
  #  @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."

      render "new"
    end
  end

  def update
  #  @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render 'edit'
    end
  end

  def destroy
  #  @project = Project.find(params[:id])
    @project.destroy

    flash[:notice] = "Project has been destroyed."

    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:name, :description)
    end

    def set_project
      @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking" +
                      " for could not be found."
      redirect_to projects_path
    end

  #  def authorize_admin!
  #    require_signin!

  #    unless current_user.admin?
  #      flash[:alert] = "You must be an admin to do that"
  #      redirect_to root_path
  #    end
  #  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %>
      prohibited this project from being saved: </h2>

    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>
  <%= f.label :name %> <br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :description %> <br>
  <%= f.text_field :description %>
</p>

<p>
  <%= f.submit 'Save Project', :class => 'btn btn-info' %>
</p>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1 class="text-center">Projects</h1>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>
<div class="row">
  <% admins_only do %>
    <%= link_to "New Project", new_project_path, class: 'btn btn-info' %>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="row">
  <h2>New Project</h2>

  <%= render "form" %>

</div>

<div class="row">
  <%= link_to 'Back Home', root_path , class: 'btn btn-info' %>
</div>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<div class="row">
  <div class="col-md-6">
    <%= @project.description %>
  </div>
</div>

<div class="btn-group">
  <%= link_to "Delete Project",
      project_path(@project),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this project?"},
      class: 'btn btn-info'
      %>
  <%= link_to "Edit Project", edit_project_path(@project), class: 'btn btn-info' %>
  <% authorized?(:"create tickets", @project) do %>
    <%= link_to "New Ticket", new_project_ticket_path(@project) %>
  <% end %>
  <%= link_to 'Back Home', root_path , class: 'btn btn-info' %>
</div>

<ul id="tickets">
  <% @project.tickets.each do |ticket| %>
    <li>
      <%= render ticket.state if ticket.state %>
      #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>

<% admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project", project_path(@project),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this Project?" } %>
<% end %>