config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
      resources :states do
        member do
          get :make_default
        end
      end

      put "permissions", to: "permissions#set",
                        as: "set_permissions"
    end
  end

  root "projects#index"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"

  delete "/signout", to: "sessions#destroy", as: "signout"

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  resources :users
  resources :files
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  validates :email, presence: true

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:email)
  end

  def new
    @user = User.new
  end

  def show

  end

  def create
    params = user_params.dup
    params[:password_confirmation] = params[:password]
    @user = User.new(params)

    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render :action => "new"
    end
  end

  def edit

  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update_attributes(params[:user], :as => :admin)
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash[:alert] = "User has not been updated."
      render action: 'edit'
    end
  end

  def destroy
    if @user == current user
      flash[:alert] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User has been deleted."
    end

    redirect_to admin_users_path
  end

  private

    def user_params
      params.require(:user).permit(:name,
                                    :email,
                                    :password,
                                    :password_confirmation,
                                    :admin)
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  scope :by_name, -> { order(:name) }

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id 
      flash[:notice] = "You have signed up succesfully."
      redirect_to projects_path
    else
      render :new
    end
  end

  def show
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
        <ul>
          <% @user.errors.full_message.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.check_box :admin %>
    <%= f.label :admin, "Is an admin?" %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<h2>Editing a User</h2>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>
<ul id="users">
  <% @users.each do |user| %>
    <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

app/views/admin/users/new.html.erb
<h2>New User</h2>
<%= render "form" %>

app/views/admin/users/show.html.erb
<h2><%= @user %></h2>
<%= link_to "Edit User", edit_admin_user_path(@user) %>
<%= link_to "Delete User", admin_user_path(@user), method: :delete,
  data: { confirm: "Are you sure you want to delete this user?" }%>
<%= link_to "Permissions", admin_user_permissions_path(@user) %>