config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
      resources :states do
        member do
          get :make_default
        end
      end

      put "permissions", to: "permissions#set",
                        as: "set_permissions"
    end
  end

  root "projects#index"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"

  delete "/signout", to: "sessions#destroy", as: "signout"

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  resources :users
  resources :files
end

app/models/state.rb
class State < ActiveRecord::Base

  def to_s
    name
  end

  def default!
    current_default_state = State.find_by_default(true)
    <co id="ch10_813_1"/>

    self.default = true
    self.save!

    if current_default_state <co id="ch10_813_2"/>
      current_default_state.default = false
      current_default_state.save!
    end
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController

  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(params[:state])
    if @state.save
      flash[:notice] = "State has been created."
      redirect_to admin_states_path
    else
      flash[:alert] = "State has not been created."
      render :action => "new"
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.default! <co id="ch10_802_1" />

    flash[:notice] = "#{@state.name} is now the default state."
    redirect_to admin_states_path
  end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
  <%= f.submit %>
<% end %>

app/views/admin/states/index.html.erb
<%= link_to "New State", new_admin_state_path %>

<ul id='states'>
  <% for state in @states %>
    <li id='state_<%= state.id %>'>
      <%= state.name %>
      <%= link_to "Make Default",
          make_default_admin_state_path(state) %>  
    </li>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<h1>New State</h1>
<%= render 'form' %>